[package]
name = "exploiting_server_side_parameter_pollution_in_a_query_string"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
reqwest = { version = "0.11.20", features = ["blocking"] }
text-colorizer = "1.0.0"
regex = "1.10.0"
select = "0.6.0"
lazy_static = "1.4.0"
