[package]
name = " source_code_disclosure_via_backup_files"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.6.0"
reqwest = { version = "0.11.20", features = ["blocking"] }
text-colorizer = "1.0.0"
lazy_static = "1.4.0"
